### PR TITLE
Task 4: Cloud Databases Overview of DB solutions

### PR DESCRIPTION
**Pull request by uniorunr**
API: https://aj7bc2l319.execute-api.eu-west-1.amazonaws.com/dev/
GET products: https://aj7bc2l319.execute-api.eu-west-1.amazonaws.com/dev/products
GET product by id: https://aj7bc2l319.execute-api.eu-west-1.amazonaws.com/dev/products/72162b2f-bc3c-4bf8-8652-6dae8ddeae35
POST product: https://aj7bc2l319.execute-api.eu-west-1.amazonaws.com/dev/products

FE CloudFront link with applied changes: https://dp1bpkg74fime.cloudfront.net/

Everything is done except Transaction based creation of product

### CODE REVIEW

**Comment by kirill-ianchuk** [comment]
@uniorunr POST /products endpoint returned 200 OK, but I wasn't able to see the new product in the response of GET /products endpoint

**Comment by uniorunr** [comment]
@kirill-ianchuk 
Yeah, sorry. I just worked with Database on some fixes so that's why the product request wasn't available.
Please try again now

**Comment by dartwlad** [comment]
Post request is forbidden for now.
image
Also please fix the product Shema, should be id, title, count, price, description.

**Comment by uniorunr** [comment]
@dartwlad 
It's strange. Just tested POST method via Postman and it seems everything is working fine
image

Good point about product schema. I'll fix it

**Comment by dartwlad** [comment]
https://dp1bpkg74fime.cloudfront.net/admin/product-form/
Please check this link and integrate products adding form with creation lambda

**Comment by uniorunr** [comment]
@dartwlad 
Get it!

**Comment by kalitamih** [comment]
This request returns "Internal server error" instead of status 400.
{
    "title": "reviewTask",
    "description": "Task review",
    "price": "b",
    "count": 12,
    "img": "https://images-na.ssl-images-amazon.com/images/I/71I8LoKn%2BOL._SX466_.jpg"
}

There is CORS problem in frontend during creation product.

**Pull request merged**
